<head>
    <style>
        h1{
            text-align:center;
            padding:400px;
        }
        .hide-bottom{
            positon:fixed;
            bottom:0;
            left:0;
            width:100%;
        }
    </style>
</head>
<body>
    <div>
        <h1>沙雕被骗了吧</h1>
    <div class ="hide-bottom"><?='405 4';?></div>
    </div>
</body>
